galaxy_info:
  author: VSG Engineering
  description: configure apache flink
  company: Comcast
  license: Proprietary
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: []
dependencies: []
